services:
  db:
    image: postgres:17
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=multiversus
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
