INSERT INTO universos (nombre, creador, fecha, descripcion, imagen) VALUES
('Dragon Ball', 'Akira Toriyama', '1984', 'Una serie de anime y manga que sigue las aventuras de Goku, un joven guerrero que busca las bolas de dragón y entrena para convertirse en el más fuerte del universo.', 'https://static.wikia.nocookie.net/dragonball/images/1/12/Dragon_Ball_Super_official_logo.png/revision/latest?cb=20161222173214&path-prefix=es'),
('Naruto', 'Masashi Kishimoto', '1999', 'Un joven ninja llamado Naruto Uzumaki persigue su sueño de convertirse en Hokage, el líder más fuerte de su aldea.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Naruto_logo.svg/960px-Naruto_logo.svg.png'),
('One Piece', 'Eiichiro Oda', '1997', 'Un grupo de piratas, encabezado por Monkey D. Luffy, viaja por el mundo en busca del legendario tesoro conocido como el One Piece.', 'https://logos-world.net/wp-content/uploads/2021/09/One-Piece-Logo.png');
('My Hero Academia', 'Kohei Horikoshi', '2014', 'En un mundo donde la mayoría de las personas tienen superpoderes, Izuku Midoriya, un joven sin poderes, sueña con convertirse en un héroe.', 'https://upload.wikimedia.org/wikipedia/commons/1/18/My_Hero_Academia_logo_in_Japan_20150106.png');
('La Vida Real', 'Dios todopoderoso', '0', 'El universo en el que vivimos los humanos.', 'https://cdn.pixabay.com/photo/2016/04/24/05/16/world-1348808__340.png.jpg');

INSERT INTO personajes (nombre, origen_id, descripcion, poder, imagen) VALUES
('Goku', 1, 'Un guerrero Saiyan con habilidades sobrehumanas y un corazón puro.', 'Kamehameha', 'https://www.superherotoystore.com/cdn/shop/articles/e33c2fa94c03efa06678116f80d62d0d_708x.jpg?v=1590599656'),
('Naruto Uzumaki', 2, 'Un ninja con un espíritu indomable y el sueño de convertirse en Hokage.', 'Rasengan', 'https://i.pinimg.com/736x/f0/46/f1/f046f16506c98144475c3708ea99ba72.jpg'),
('Monkey D. Luffy', 3, 'El capitán de los Piratas del Sombrero de Paja con el poder de la fruta del diablo Gomu Gomu no Mi.', 'Gomu Gomu no Pistol', 'https://static.wikia.nocookie.net/onepiece/images/c/c3/Monkey_D._Luffy_Anime_Debut_Infobox.png/revision/latest?cb=20240826011447&path-prefix=es');
('Izuku Midoriya', 4, 'Un joven sin poderes que hereda el poder del héroe All Might.', 'One For All', 'https://i.pinimg.com/736x/8a/cd/1f/8acd1f6f63123bc9b3a9c72475b4993f.jpg');
('Roronoa Zoro', 3, 'El espadachín más fuerte, con un estilo único de tres espadas. Su objetivo es convertirse en el mejor espadachín del mundo.', 'Santoryu, Ashura', 'https://i.pinimg.com/736x/35/82/70/358270af6d82c1051be279df4bc94c3e.jpg'),
('Nami', 3, 'La navegante de los Piratas de Sombrero de Paja, conocida por su astucia, habilidades con mapas y el clima.', 'Clima-Tact', 'https://static.wikia.nocookie.net/onepiece/images/0/0c/Nami_Anime_Dos_A%C3%B1os_Despu%C3%A9s_Infobox.png/revision/latest?cb=20191125191158&path-prefix=es');
('Vegeta', 1, 'Príncipe de los saiyajins, inicialmente un rival de Goku, pero luego un aliado que se convierte en uno de los luchadores más fuertes.', 'Final Flash, Big Bang Attack', 'https://depor.com/resizer/uGKEQvDmDIYXQOXfiA0ukneujoI=/1200x1200/smart/filters:format(jpeg):quality(90)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/4HFH2SWZ35E3BE6VXIRA6X2EZA.jpg'),
('Frieza', 1, 'Uno de los villanos más temidos del universo, líder del ejército de la Fuerza Especial, conocido por su crueldad y gran poder.', 'Death Beam, Golden Frieza', 'https://static.wikia.nocookie.net/humanoid/images/4/4a/FriezaFinalFormNV..png/revision/latest?cb=20130228200016');
('Manuel Camejo', 5, 'Profesor de Cátedra de Introduccion al Desarollo Software.', '*Ruido de mate*', 'https://media.licdn.com/dms/image/v2/C4E03AQF1b8sEvMsZLQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1591644782813?e=2147483647&v=beta&t=xJm5Yc47SeQ29KpuSXkYgdn5OLjlX8cTsdi7HuFYg7E');

INSERT INTO lugares (nombre, descripcion, origen_id, tipo, imagen) VALUES
('Konoha', 'La aldea oculta entre las hojas, hogar de muchos ninjas.', 2, 'Aldea Ninja', 'https://wallpapers.com/images/featured/konoha-kwldytpkkc1uo4qb.jpg'),
('Isla Sabaody', 'Un archipiélago donde los piratas se preparan para entrar al Nuevo Mundo.', 3, 'Isla', 'https://static.wikia.nocookie.net/onepiece/images/5/52/Archipi%C3%A9lago_Sabaody.png/revision/latest?cb=20160929175248&path-prefix=es'),
('Planeta Namek', 'El planeta natal de los Namekianos y un lugar sagrado para los dragones.', 1, 'Planeta', 'https://pm1.aminoapps.com/7953/d3de6bcd702111dfe5d13c1b1af1b4653b03f9b0r1-542-286v2_hq.jpg');
('Academia UA', 'Una prestigiosa academia para héroes en formación.', 4, 'Academia', 'https://i.pinimg.com/736x/07/96/3a/07963a33f30a7c69dee70432aad9fec6.jpg');
('Dressrosa', 'Una isla controlada por Doflamingo, conocida por su cultura y lucha por la libertad.', 3, 'Isla', 'https://m.media-amazon.com/images/M/MV5BZDkyZGFiYWMtZjk0Yi00ODA0LTk1ZDktMzY0ZGFjNTVjNmY1XkEyXkFqcGc@._V1_.jpg');
('Monte Myoboku', 'Un lugar sagrado y místico donde Naruto recibe entrenamiento y tiene contacto con los sapos.', 2, 'Montaña', 'https://static.wikia.nocookie.net/akatsukiafterlife/images/9/9e/Monte_Myobokuzan.png/revision/latest?cb=20151215181500&path-prefix=es'),
('La Sala del Consejo', 'Un lugar donde los líderes de las aldeas ninja se reúnen para discutir los eventos del mundo ninja.', 2, 'Edificio', 'https://static.wikia.nocookie.net/narutoinuyashapokemnyharrypotter/images/b/b6/Consejo_de_Konoha.png/revision/latest?cb=20130509215159&path-prefix=es');
('Planeta Vegeta', 'El planeta natal de los saiyajins, destruido por Frieza.', 1, 'Planeta', 'https://static.wikia.nocookie.net/dragonball/images/7/73/Planeta_Vegeta_DBS_Broly.png/revision/latest?cb=20181006224231&path-prefix=es'),
('Salón de la Eternidad', 'Un lugar místico donde los guerreros entrenan y se enfrentan a pruebas extremas. Es el escenario de la lucha entre los más poderosos.', 1, 'Lugar Sagrado', 'https://static.wikia.nocookie.net/dragonball/images/1/1e/Fondo_de_la_Sala_del_Alma_y_el_Tiempo_en_Legends.png/revision/latest?cb=20210529005541&path-prefix=es');
('Edificio de la FIUBA', 'Un lugar místico donde estudiantes entrenan y se enfrentan a pruebas extremas.', 5, 'Edificio', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Buenos_Aires_-_UBA_-_FIUBA_Paseo_Col%C3%B3n_2.jpg/1024px-Buenos_Aires_-_UBA_-_FIUBA_Paseo_Col%C3%B3n_2.jpg');


